version: "3"
services:
  springboot-backend:
    image: employee-manage-springboot
    ports:
      - "8080:8080"
    networks:
      - employee_mange
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    container_name: springboot-backend
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:8
    networks:
      - employee_mange
    environment:
      - MYSQL_DATABASE=employee_management_system
      - MYSQL_ROOT_PASSWORD=root
    container_name: mysql_db
networks:
  employee_mange:


